/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author david
 */
public class VistaBase extends javax.swing.JFrame {

    /**
     * Creates new form VistaBase
     */
    public VistaBase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        propietarios = new javax.swing.JMenuItem();
        registropro = new javax.swing.JMenuItem();
        actpro = new javax.swing.JMenuItem();
        Propietario = new javax.swing.JMenu();
        residentes = new javax.swing.JMenuItem();
        registroresi = new javax.swing.JMenuItem();
        actures = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        trabajadores = new javax.swing.JMenuItem();
        registrotrab = new javax.swing.JMenuItem();
        acttrab = new javax.swing.JMenuItem();
        tipoem = new javax.swing.JMenuItem();
        tipoturn = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        regisuser = new javax.swing.JMenuItem();
        regiscar = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        actpar = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        visitante = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        actapa = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel3.setText("jLabel3");

        jMenu5.setText("jMenu5");

        jMenu8.setText("File");
        jMenuBar2.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar2.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(407, 557, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        jMenu1.setText("Propietarios");

        propietarios.setText("Visualizar Propietarios");
        propietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietariosActionPerformed(evt);
            }
        });
        jMenu1.add(propietarios);

        registropro.setText("Registro Porpietarios");
        jMenu1.add(registropro);

        actpro.setText("Actualizar o eliminar un  propietario");
        actpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actproActionPerformed(evt);
            }
        });
        jMenu1.add(actpro);

        jMenuBar1.add(jMenu1);

        Propietario.setText("Residentes");

        residentes.setText("Visualizar Residentes");
        Propietario.add(residentes);

        registroresi.setText("Registro Residentes");
        Propietario.add(registroresi);

        actures.setText("Actualizar o eliminar un  residente");
        actures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acturesActionPerformed(evt);
            }
        });
        Propietario.add(actures);

        jMenuBar1.add(Propietario);

        jMenu2.setText("Trabajadores");

        trabajadores.setText("Visualizar Trabajadores");
        jMenu2.add(trabajadores);

        registrotrab.setText("Registro Trabajador");
        registrotrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrotrabActionPerformed(evt);
            }
        });
        jMenu2.add(registrotrab);

        acttrab.setText("Actualizar o eliminar un trabajador");
        jMenu2.add(acttrab);

        tipoem.setText("Registrar un tipo de empleado");
        jMenu2.add(tipoem);

        tipoturn.setText("Registrar un tipo de turno");
        jMenu2.add(tipoturn);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Usuarios");

        regisuser.setText("Registrar un usuario");
        jMenu6.add(regisuser);

        jMenuBar1.add(jMenu6);

        regiscar.setText("Carros");

        jMenuItem3.setText("Registrar un carro");
        regiscar.add(jMenuItem3);

        actpar.setText("Actualizar un parqueadero");
        regiscar.add(actpar);

        jMenuBar1.add(regiscar);

        jMenu7.setText("Visitantes ");

        visitante.setText("Historial de visitante");
        jMenu7.add(visitante);

        jMenuBar1.add(jMenu7);

        jMenu10.setText("Pagos");

        jMenuItem2.setText("Generar Recibos");
        jMenu10.add(jMenuItem2);

        jMenuItem4.setText("Consultar una Factura");
        jMenu10.add(jMenuItem4);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Apartamento");

        actapa.setText("Actualizar el propietario de un apartamento");
        jMenu11.add(actapa);

        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actproActionPerformed

    private void acturesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acturesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acturesActionPerformed

    private void propietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propietariosActionPerformed

    private void registrotrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrotrabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrotrabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Propietario;
    public javax.swing.JMenuItem actapa;
    public javax.swing.JMenuItem actpar;
    public javax.swing.JMenuItem actpro;
    public javax.swing.JMenuItem acttrab;
    public javax.swing.JMenuItem actures;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    public javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenuItem propietarios;
    public javax.swing.JMenu regiscar;
    public javax.swing.JMenuItem registropro;
    public javax.swing.JMenuItem registroresi;
    public javax.swing.JMenuItem registrotrab;
    public javax.swing.JMenuItem regisuser;
    public javax.swing.JMenuItem residentes;
    public javax.swing.JMenuItem tipoem;
    public javax.swing.JMenuItem tipoturn;
    public javax.swing.JMenuItem trabajadores;
    public javax.swing.JMenuItem visitante;
    // End of variables declaration//GEN-END:variables
}
